// Code generated by "stringer -type NodeType"; DO NOT EDIT.

package linetmpl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TEXT-0]
	_ = x[ACTION-1]
	_ = x[PIPE-2]
	_ = x[COMMAND-3]
	_ = x[VARIABLE-4]
	_ = x[IDENTIFIER-5]
	_ = x[DOT-6]
	_ = x[NIL-7]
	_ = x[FIELD-8]
	_ = x[CHAIN-9]
	_ = x[BOOL-10]
	_ = x[NUMBER-11]
	_ = x[STRING-12]
}

const _NodeType_name = "TEXTACTIONPIPECOMMANDVARIABLEIDENTIFIERDOTNILFIELDCHAINBOOLNUMBERSTRING"

var _NodeType_index = [...]uint8{0, 4, 10, 14, 21, 29, 39, 42, 45, 50, 55, 59, 65, 71}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return "NodeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
